import numpy as np

np.random.seed(0)

print("=" * 80)
print("EP3 Part 2: Aggregations")
print("=" * 80)

print("\n1) Python sum vs NumPy sum")
L = np.random.random(100)
print("sum(L)    =", sum(L))
print("np.sum(L) =", np.sum(L))

print("\n2) Min, Max, Sum")
big_array = np.random.rand(20)
print("data =", big_array)
print("np.min =", np.min(big_array))
print("np.max =", np.max(big_array))
print("np.sum =", np.sum(big_array))
print("method min =", big_array.min())
print("method max =", big_array.max())
print("method sum =", big_array.sum())

print("\n3) Aggregation with 2D Array")
M = np.random.random((3, 4))
print("M =")
print(M)
print("M.sum() =", M.sum())
print("M.min(axis=0) =", M.min(axis=0))
print("M.max(axis=1) =", M.max(axis=1))

print("\n4) Understanding axis")
M_axis = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("M_axis =")
print(M_axis)
print("sum all =", M_axis.sum())
print("sum axis=0 =", M_axis.sum(axis=0))
print("sum axis=1 =", M_axis.sum(axis=1))

print("\n5) Common Aggregations")
data = np.array([120, 135, 110, 98, 145, 160, 175, 130, 125, 140])
print("data =", data)
print("mean =", np.mean(data))
print("median =", np.median(data))
print("std =", np.std(data))
print("var =", np.var(data))
print("min =", np.min(data))
print("max =", np.max(data))
print("argmin =", np.argmin(data))
print("argmax =", np.argmax(data))
print("p25 =", np.percentile(data, 25))
print("p50 =", np.percentile(data, 50))
print("p75 =", np.percentile(data, 75))

print("\n6) Boolean Aggregation")
print("any data > 170 =", np.any(data > 170))
print("all data > 50 =", np.all(data > 50))

print("\n7) NaN-safe Functions")
x = np.array([1, 2, np.nan, 4, 5])
print("x =", x)
print("sum =", np.sum(x))
print("mean =", np.mean(x))
print("nansum =", np.nansum(x))
print("nanmean =", np.nanmean(x))
print("nanmin =", np.nanmin(x))
print("nanmax =", np.nanmax(x))
print("nanmedian =", np.nanmedian(x))
print("nanpercentile 50 =", np.nanpercentile(x, 50))

print("\n8) Example: API Response Time")
api_response_ms = np.array([120, 135, 110, 98, 145, 160, 175, 130, 125, 140])
print("Mean:   ", np.mean(api_response_ms))
print("Std:    ", np.std(api_response_ms))
print("Min:    ", np.min(api_response_ms))
print("Max:    ", np.max(api_response_ms))
print("Median: ", np.median(api_response_ms))
print("P75:    ", np.percentile(api_response_ms, 75))

print("\n9) Example: Sensor Temperature")
temperature = np.array([29.5, 30.1, 30.0, 29.8, 31.2, 32.5, 33.0, 31.8, 30.6])
print("Mean: ", temperature.mean())
print("Min:  ", temperature.min())
print("Max:  ", temperature.max())
print("P25:  ", np.percentile(temperature, 25))
print("P50:  ", np.median(temperature))
print("P75:  ", np.percentile(temperature, 75))
